// Code generated by docuconf. DO NOT EDIT.
package orders_batch

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name: "orders-batch"
		generator: {
			language: "cobol"
			sdk:      "docuconf-cobol"
			version:  "0.1.0"
		}
	}
	vars: {
		// Each item must fit CFG-ALLOWED-ORIGINS (64 bytes). The contract cannot state an item length
		// yet, so the COBOL loader rejects a longer item at boot (out_of_range).
		ALLOWED_ORIGINS: {
			type:        "list"
			description: "Origins whose orders the job accepts"
			default: ["http://localhost:3000"]
			encoding:  "csv"
			items:     "string"
			separator: ","
			minItems:  1
			maxItems:  8
		}
		// The value must fit CFG-DATABASE-URL (200 bytes). The contract cannot state a url's length,
		// so the COBOL loader rejects a longer value at boot (out_of_range).
		DATABASE_URL: {
			type:        "url"
			description: "Postgres connection string of the orders database"
			required:    true
			secret:      true
			schemes: ["postgres"]
		}
		LOG_LEVEL: {
			type:        "enum"
			description: "Log verbosity"
			default:     "info"
			values: ["debug", "info", "warn", "error"]
		}
		PORT: {
			type:        "int"
			description: "Port of the Prometheus metrics endpoint"
			default:     8080
			min:         1
			max:         65535
		}
		REQUEST_TIMEOUT: {
			type:        "duration"
			description: "Time allowed for each database call, in milliseconds"
			default:     "30s"
			min:         "1s"
			max:         "5m"
			encoding:    "go"
		}
		WORKER_COUNT: {
			type:        "int"
			description: "Number of workers that share the input"
			default:     4
			min:         1
			max:         64
		}
	}
	files: {
		orders: {
			type:        "text"
			description: "The orders to summarise, one per line"
			required:    true
			path:        "/data/orders.txt"
			pathEnv:     "ORDERS_FILE"
			maxSize:     1048576
		}
	}
}
