// Package tests runs the shared docuconf conformance suite (SPEC §12)
// through the COBOL boot path: docuconf exec validates each case's
// environment against its contract, then starts a COBOL program that
// CALLs a loader generated by docuconf-cobol, and the values the loader
// stored in the record are compared with the case's expectations.
//
// It needs cobc (GnuCOBOL 3) and the docuconf CLI (DOCUCONF, else
// docuconf on PATH), and reads cases.json from DOCUCONF_CONFORMANCE,
// else ../../docuconf-go/conformance/cases.json. Without them it skips,
// unless DOCUCONF_REQUIRE_CONFORMANCE=1.
package tests

import (
	"bufio"
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math/big"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"slices"
	"strconv"
	"strings"
	"testing"
	"time"

	docuconf "github.com/docuconf/docuconf-go"

	"github.com/docuconf/docuconf-cobol/internal/gen"
)

type confCase struct {
	ID       string            `json:"id"`
	Requires []string          `json:"requires"`
	Contract json.RawMessage   `json:"contract"`
	Env      map[string]string `json:"env"`
	Expect   map[string]any    `json:"expect"`
	Errors   []struct {
		Var  string `json:"var"`
		Code string `json:"code"`
	} `json:"errors"`
}

// unsupported lists the cases the COBOL loader cannot represent, with
// the reason. It is empty: every case runs.
var unsupported = map[string]string{}

// String fields are this wide; values are compared without the
// trailing spaces a COBOL field pads them with.
const strWidth = 512

func require() bool {
	return os.Getenv("DOCUCONF_REQUIRE_CONFORMANCE") == "1"
}

func skipOrFail(t *testing.T, format string, args ...any) {
	t.Helper()
	if require() {
		t.Fatalf(format, args...)
	}
	t.Skipf(format, args...)
}

// tools finds cobc and the docuconf CLI.
func tools(t *testing.T) (cobc, dc string) {
	t.Helper()
	cobc, err := exec.LookPath("cobc")
	if err != nil {
		skipOrFail(t, "cobc (GnuCOBOL) not found")
	}
	dc = os.Getenv("DOCUCONF")
	if dc == "" {
		dc, err = exec.LookPath("docuconf")
		if err != nil {
			skipOrFail(t, "the docuconf CLI was not found; set DOCUCONF to its path")
		}
	}
	return cobc, dc
}

func loadCases(t *testing.T) []confCase {
	t.Helper()
	p := os.Getenv("DOCUCONF_CONFORMANCE")
	if p == "" {
		p = filepath.Join("..", "..", "docuconf-go", "conformance", "cases.json")
	}
	data, err := os.ReadFile(p)
	if err != nil {
		skipOrFail(t, "conformance cases not found at %s: %v", p, err)
	}
	var doc struct {
		Cases []confCase `json:"cases"`
	}
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.UseNumber()
	if err := dec.Decode(&doc); err != nil {
		t.Fatal(err)
	}
	return doc.Cases
}

func TestConformance(t *testing.T) {
	cobc, dc := tools(t)
	cases := loadCases(t)
	built := map[string]*driver{}
	var expectN, errorN, skipped int
	for _, c := range cases {
		key := string(c.Contract)
		if built[key] == nil {
			d, err := buildDriver(t, cobc, c.Contract)
			if err != nil {
				t.Fatalf("%s: %v", c.ID, err)
			}
			built[key] = d
		}
		d := built[key]
		t.Run(c.ID, func(t *testing.T) {
			if why, skip := unsupported[c.ID]; skip {
				skipped++
				t.Skip(why)
			}
			stdout, stderr, code := d.run(t, dc, c.Env)
			if len(c.Errors) > 0 {
				errorN++
				if code != 1 {
					t.Fatalf("docuconf exec exited %d, want 1\nstderr:\n%s", code, stderr)
				}
				if strings.Contains(stdout, "DRIVER") {
					t.Fatalf("the program ran despite the problems")
				}
				for _, e := range c.Errors {
					if !hasViolation(stderr, e.Var, e.Code) {
						t.Errorf("want %s (%s) in:\n%s", e.Var, e.Code, stderr)
					}
				}
				return
			}
			expectN++
			if code != 0 {
				t.Fatalf("exit %d\nstdout:\n%s\nstderr:\n%s", code, stdout, stderr)
			}
			got, err := d.parse(stdout)
			if err != nil {
				t.Fatalf("%v\nstdout:\n%q", err, stdout)
			}
			for name, want := range c.Expect {
				if err := compare(d.vars[name], got[name], want); err != nil {
					t.Errorf("%s: %v", name, err)
				}
			}
		})
	}
	t.Logf("conformance: %d cases (%d with typed values checked in the COBOL record, %d rejected by docuconf exec before the program starts), %d skipped",
		len(cases), expectN, errorN, skipped)
}

func hasViolation(out, name, code string) bool {
	for _, l := range strings.Split(out, "\n") {
		l = strings.TrimSpace(l)
		if strings.HasPrefix(l, name+":") && strings.HasSuffix(l, "("+code+")") {
			return true
		}
	}
	return false
}

type cvar struct {
	name, typ, items, field, count, present string
}

type driver struct {
	dir      string
	bin      string
	contract string
	vars     map[string]*cvar
	order    []string
}

// buildDriver writes a copybook declaring the case contract's variables,
// generates its loader, and compiles a program that CALLs it and prints
// every field.
func buildDriver(t *testing.T, cobc string, contractJSON []byte) (*driver, error) {
	var doc struct {
		Vars map[string]map[string]any `json:"vars"`
	}
	dec := json.NewDecoder(bytes.NewReader(contractJSON))
	dec.UseNumber()
	if err := dec.Decode(&doc); err != nil {
		return nil, err
	}
	dir := t.TempDir()
	d := &driver{dir: dir, vars: map[string]*cvar{}}
	for n := range doc.Vars {
		d.order = append(d.order, n)
	}
	slices.Sort(d.order)

	var cpy strings.Builder
	cpy.WriteString("      *> @service conformance  @program CASECFG\n")
	cpy.WriteString("       01  CASE-CONFIG.\n")
	for i, n := range d.order {
		v := doc.Vars[n]
		cv := &cvar{name: n, typ: v["type"].(string), field: fmt.Sprintf("F-%d", i+1),
			present: fmt.Sprintf("P-%d", i+1), count: fmt.Sprintf("C-%d", i+1)}
		d.vars[n] = cv
		tags := []string{"@env " + n, "@present " + cv.present}
		if v["required"] == true {
			tags = append(tags, "@required")
		}
		if def, ok := v["default"]; ok {
			tags = append(tags, "@default "+defaultWords(cv.typ, def))
		}
		pic := ""
		switch cv.typ {
		case "string":
			pic = fmt.Sprintf("PIC X(%d)", strWidth)
		case "url", "json":
			pic = fmt.Sprintf("PIC X(%d)", strWidth)
			tags = append(tags, "@type "+cv.typ)
		case "enum":
			pic = "PIC X(64)"
			vals := []string{}
			for _, x := range v["values"].([]any) {
				vals = append(vals, quote(x.(string)))
			}
			tags = append(tags, "@type enum", "@values "+strings.Join(vals, " "))
		case "int":
			pic = "PIC S9(19)"
		case "float":
			pic = "PIC S9(18)V9(18)"
		case "bool":
			pic = "PIC X"
			tags = append(tags, "@type bool")
		case "duration":
			pic = "PIC S9(18)"
			tags = append(tags, "@unit ns", "@encoding "+v["encoding"].(string))
		case "list":
			cv.items = v["items"].(string)
			if cv.items == "int" {
				pic = "PIC S9(19) OCCURS 20"
			} else {
				pic = fmt.Sprintf("PIC X(%d) OCCURS 20", strWidth)
			}
			tags = append(tags, "@count "+cv.count, "@encoding "+v["encoding"].(string))
			if s, ok := v["separator"].(string); ok {
				tags = append(tags, "@separator "+quote(s))
			}
		default:
			return nil, fmt.Errorf("%s: type %s", n, cv.typ)
		}
		fmt.Fprintf(&cpy, "      *> %s\n", strings.ReplaceAll(v["description"].(string), "\n", " "))
		for _, tg := range tags {
			fmt.Fprintf(&cpy, "      *> %s\n", tg)
		}
		fmt.Fprintf(&cpy, "           05  %s %s.\n", cv.field, pic)
		fmt.Fprintf(&cpy, "           05  %s PIC X.\n", cv.present)
		if cv.typ == "list" {
			fmt.Fprintf(&cpy, "           05  %s PIC 9(4).\n", cv.count)
		}
	}
	if err := os.WriteFile(filepath.Join(dir, "case.cpy"), []byte(cpy.String()), 0o644); err != nil {
		return nil, err
	}
	c, err := gen.Load(filepath.Join(dir, "case.cpy"), gen.Options{})
	if err != nil {
		return nil, fmt.Errorf("generate:\n%v\ncopybook:\n%s", err, cpy.String())
	}
	if _, err := c.ContractCUE(); err != nil {
		return nil, fmt.Errorf("the generated contract: %v", err)
	}
	loader, err := c.Loader()
	if err != nil {
		return nil, err
	}
	if err := os.WriteFile(filepath.Join(dir, "CASECFG.cbl"), loader, 0o644); err != nil {
		return nil, err
	}
	// docuconf exec checks against the case's own contract.
	cue, err := docuconf.ContractCUE(contractJSON, "conformance")
	if err != nil {
		return nil, err
	}
	d.contract = filepath.Join(dir, "contract.cue")
	if err := os.WriteFile(d.contract, cue, 0o644); err != nil {
		return nil, err
	}

	var prog strings.Builder
	prog.WriteString(`       IDENTIFICATION DIVISION.
       PROGRAM-ID. DRIVER.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       COPY "case.cpy".
       01  D-NUM PIC -(20)9.
       01  D-FLT PIC -(19)9.9(18).
       01  D-K   PIC 9(4).
       PROCEDURE DIVISION.
           CALL "CASECFG" USING CASE-CONFIG
           IF RETURN-CODE NOT = 0
               STOP RUN RETURNING 3
           END-IF
           DISPLAY "DRIVER" END-DISPLAY
`)
	for _, n := range d.order {
		cv := d.vars[n]
		if cv.typ == "list" {
			fmt.Fprintf(&prog, "           DISPLAY \"L\" %s %s END-DISPLAY\n", cv.present, cv.count)
			fmt.Fprintf(&prog, "           PERFORM VARYING D-K FROM 1 BY 1 UNTIL D-K > %s\n", cv.count)
			prog.WriteString(display(cv.items, cv.field+"(D-K)", `"I"`))
			prog.WriteString("           END-PERFORM\n")
			continue
		}
		prog.WriteString(display(cv.typ, cv.field, `"V" `+cv.present))
	}
	prog.WriteString("           STOP RUN.\n")
	if err := os.WriteFile(filepath.Join(dir, "driver.cbl"), []byte(prog.String()), 0o644); err != nil {
		return nil, err
	}
	d.bin = filepath.Join(dir, "driver")
	cmd := exec.Command(cobc, "-x", "-o", d.bin, "driver.cbl", "CASECFG.cbl")
	cmd.Dir = dir
	if out, err := cmd.CombinedOutput(); err != nil {
		return nil, fmt.Errorf("cobc: %v\n%s", err, out)
	}
	return d, nil
}

func display(typ, field, prefix string) string {
	switch typ {
	case "int", "duration":
		return fmt.Sprintf("           MOVE %s TO D-NUM\n           DISPLAY %s D-NUM END-DISPLAY\n", field, prefix)
	case "float":
		return fmt.Sprintf("           MOVE %s TO D-FLT\n           DISPLAY %s D-FLT END-DISPLAY\n", field, prefix)
	}
	return fmt.Sprintf("           DISPLAY %s %s END-DISPLAY\n", prefix, field)
}

func quote(s string) string { return `"` + strings.ReplaceAll(s, `"`, `""`) + `"` }

func defaultWords(typ string, def any) string {
	switch typ {
	case "list":
		var w []string
		for _, x := range def.([]any) {
			w = append(w, quote(fmt.Sprint(x)))
		}
		return strings.Join(w, " ")
	case "json":
		b, _ := json.Marshal(def)
		return quote(string(b))
	}
	return quote(fmt.Sprint(def))
}

// run starts docuconf exec on the driver with exactly env.
func (d *driver) run(t *testing.T, dc string, env map[string]string) (stdout, stderr string, code int) {
	t.Helper()
	cmd := exec.Command(dc, "exec", "-contract", d.contract, "--", d.bin)
	cmd.Env = []string{"DOCUCONF_TERMINATION_LOG=-"}
	for k, v := range env {
		cmd.Env = append(cmd.Env, k+"="+v)
	}
	var o, e bytes.Buffer
	cmd.Stdout, cmd.Stderr = &o, &e
	err := cmd.Run()
	var ee *exec.ExitError
	switch {
	case errors.As(err, &ee):
		code = ee.ExitCode()
	case err != nil:
		t.Fatal(err)
	}
	return o.String(), e.String(), code
}

type value struct {
	present bool
	text    string   // a scalar's text
	items   []string // a list's items
}

// parse reads the driver's output. String fields are printed at their
// full width, so a value holding a newline is read correctly.
func (d *driver) parse(out string) (map[string]value, error) {
	r := bufio.NewReader(strings.NewReader(out))
	readLine := func() (string, error) {
		s, err := r.ReadString('\n')
		return strings.TrimSuffix(s, "\n"), err
	}
	readFixed := func(n int) (string, error) {
		b := make([]byte, n+1)
		if _, err := io.ReadFull(r, b); err != nil {
			return "", err
		}
		return string(b[:n]), nil
	}
	if l, err := readLine(); err != nil || l != "DRIVER" {
		return nil, fmt.Errorf("no DRIVER line")
	}
	scalar := func(typ string) (string, error) {
		switch typ {
		case "int", "duration", "float":
			s, err := readLine()
			return strings.TrimSpace(s), err
		case "bool":
			return readFixed(1)
		case "enum":
			return readFixed(64)
		}
		return readFixed(strWidth)
	}
	got := map[string]value{}
	for _, n := range d.order {
		cv := d.vars[n]
		head := make([]byte, 2)
		if _, err := io.ReadFull(r, head); err != nil {
			return nil, err
		}
		v := value{present: head[1] == 'Y'}
		if cv.typ == "list" {
			cnt, err := readFixed(4)
			if err != nil {
				return nil, err
			}
			k, _ := strconv.Atoi(cnt)
			for i := 0; i < k; i++ {
				if b, _ := r.ReadByte(); b != 'I' {
					return nil, fmt.Errorf("%s: expected an item", n)
				}
				s, err := scalar(cv.items)
				if err != nil {
					return nil, err
				}
				v.items = append(v.items, s)
			}
		} else {
			s, err := scalar(cv.typ)
			if err != nil {
				return nil, fmt.Errorf("%s: %v", n, err)
			}
			v.text = s
		}
		got[n] = v
	}
	return got, nil
}

func compare(cv *cvar, got value, want any) error {
	if cv == nil {
		return fmt.Errorf("not declared")
	}
	if want == nil {
		if got.present {
			return fmt.Errorf("want unset, got %q %q", got.text, got.items)
		}
		return nil
	}
	if !got.present {
		return fmt.Errorf("unset, want %v", want)
	}
	if cv.typ == "list" {
		wl := want.([]any)
		if len(wl) != len(got.items) {
			return fmt.Errorf("got %d items %q, want %v", len(got.items), got.items, want)
		}
		for i, w := range wl {
			if err := compareScalar(cv.items, got.items[i], w); err != nil {
				return fmt.Errorf("item %d: %v", i, err)
			}
		}
		return nil
	}
	return compareScalar(cv.typ, got.text, want)
}

func compareScalar(typ, got string, want any) error {
	switch typ {
	case "string", "url", "enum":
		if strings.TrimRight(got, " ") != strings.TrimRight(want.(string), " ") {
			return fmt.Errorf("got %q, want %q", strings.TrimRight(got, " "), want)
		}
	case "json":
		var g, w any
		if err := json.Unmarshal([]byte(strings.TrimRight(got, " ")), &g); err != nil {
			return fmt.Errorf("field is not JSON: %q", got)
		}
		b, _ := json.Marshal(want)
		_ = json.Unmarshal(b, &w)
		if !reflect.DeepEqual(g, w) {
			return fmt.Errorf("got %v, want %v", g, w)
		}
	case "int":
		g, ok1 := new(big.Int).SetString(got, 10)
		w, ok2 := new(big.Int).SetString(fmt.Sprint(want), 10)
		if !ok1 || !ok2 || g.Cmp(w) != 0 {
			return fmt.Errorf("got %s, want %v", got, want)
		}
	case "float":
		g, err1 := strconv.ParseFloat(got, 64)
		w, err2 := strconv.ParseFloat(fmt.Sprint(want), 64)
		if err1 != nil || err2 != nil || g != w {
			return fmt.Errorf("got %s, want %v", got, want)
		}
	case "bool":
		if (got == "Y") != want.(bool) {
			return fmt.Errorf("got %s, want %v", got, want)
		}
	case "duration":
		w, err := time.ParseDuration(want.(string))
		g, err2 := strconv.ParseInt(got, 10, 64)
		if err != nil || err2 != nil || int64(w) != g {
			return fmt.Errorf("got %sns, want %v", got, want)
		}
	}
	return nil
}
